FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
COPY data/raw/creditcard.csv data/raw/creditcard.csv

CMD ["python", "-m", "src.drift_check"]
