
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: creditcard-fraud-mlops
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-db
  namespace: creditcard-fraud-mlops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: mlflow-db
  data:
    - secretKey: password
      remoteRef:
        key: "creditcard-fraud-mlops-mlflow-db-password"
